/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("invoice.java-application-conventions")
}

dependencies {
    implementation(project(":common"))
    implementation(project(":domain"))
}
